### ISSUE TITLE
problem for wmake

### ISSUE THREAD

**Issue by Boris3305** [gerlero/openfoam2112-app#25]
Thank u for your work for this app.
   I'm new for openfoam, and now I'm studying how to use this app. But there are some problems:
1. If I need creat the direction such as $FOAM_USER_APPBIN myself ?
2. When I use the <wmake> there are an erro code 1 happened, it said that cant output to /volumes/openfoam2112/.../bin . Is this cause by the virtual disk for openfoam is only read?
 
Thanks!

**Comment by gerlero** [comment]
Usually, you don't need to create that directory. But in any case, you can make sure that such directory exists by doing `mkdir -p $FOAM_USER_APPBIN` (and same for `$FOAM_USER_LIBBIN`, if necessary). I'm assuming you're asking this because you're trying to install a third-party extension.

`$FOAM_SITE_APPBIN` (and `$FOAM_SITE_LIBBIN`) are a different story. Those environment variables by default point to paths inside the virtual disk, which is indeed non-writable. The path you mention makes me think that the extension is trying to install binaries there. You might want to change it so that it installs into the "`USER`" directories instead. 

Changing the values of the "`SITE`" variables so that they point to someplace writable might also do it (although this _could_ be a bit hackish—I have never tried it). Note that the "`SITE`" directories are not user-writable in precompiled Linux builds as well.

**Comment by Boris3305** [comment]
I ll try it. Thank u!

**Comment by Boris3305** [comment]
I find another way run openfoam on my MAC. And I think it can help improve this work.
U may see in this site :https://github.com/mrklein/openfoam-os-x/issues/75#issuecomment-1029923388

Finally, Thank U for you work to help me step into this APP

**Comment by gerlero** [comment]
Actually, those are pretty much the same steps that this project uses to compile OpenFOAM on macOS.

It seems that the third-party extension that you're attempting to install expects/requires a user-writable OpenFOAM install (may I ask which software that is?), which the prepackaged app that you can download from here is not.

However, you _can_ get a read-write OpenFOAM DMG with this project by cloning this repo and [doing the build yourself](https://github.com/gerlero/openfoam2112-app#-build) (you'll find an `OpenFOAM-v2112-build.dmg` inside the `build` directory, which is what you seem to require).

**Comment by Boris3305** [comment]
It just the exmple in the openfoam guid complie the pisoFoam solver. When I use repo wmake, there is the error "cant write into ...". 
And the build step in README, I dont know why it doesnt work.(I'm newbie for all this linux, C++ and Openfoam) So it's hard for me knowing which part is wrong. But I'm sure the BUILD step is main reason cause this problem.

**Comment by Boris3305** [comment]
BTW, when I want to cd openfoam-app, it seems that there isnt this dir. That why  I failed BUILD

**Comment by gerlero** [comment]
I get it now. You're modifying the OpenFOAM source code directly and want to recompile it in place... Well, in that case you **need** a user-writable OpenFOAM install, which means that you should probably compile OpenFOAM yourself (as I said, you can clone this repo and do `make build` to get a writable DMG with OpenFOAM, which will let you do what you want to do).

**Comment by gerlero** [comment]
> BTW, when I want to cd openfoam-app, it seems that there isnt this dir. That why I failed BUILD

You probably need clone this repo first. E.g.:

```bash
git clone https://github.com/gerlero/openfoam2112-app.git
cd openfoam2112-app
make build
```

The `make build` command will build OpenFOAM into the writable `OpenFOAM-v2112-build.dmg` that you need, and then stop there (i.e., it won't continue and build the full OpenFOAM-v2112.app).

**Comment by Boris3305** [comment]
It seems work! I‘ll try it after .
Thank u !
